Add new entities: funders, sources, publishers
ropensci/openalexR pull request #130
Opened 2023-07-19 13:29 UTC by trangdata

Closes #124

2023-07-19 14:21 UTC, trangdata commented
@maelle Have you seen this error before for other ropensci packages? This is in our `check-pkgdown.yml` file.
https://github.com/ropensci/openalexR/blob/66f07433b5efbdff16c581da9fdb754fb649fb4b/.github/workflows/check-pkgdown.yml#L28

> Run devtools::install_github("https://github.com/ropensci-org/rotemplate")
##[debug]/usr/local/bin/Rscript /home/runner/work/_temp/ea1f9bee-1054-454b-8bf6-6055f1296b5d
Using github PAT from envvar GITHUB_PAT
Error: Error: Failed to install 'rotemplate' from GitHub:
  SSL peer certificate or SSH remote key was not OK: [api.github.com] SSL: no alternative certificate subject name matches target host name 'api.github.com'
Execution halted
Error: Process completed with exit code 1.
##[debug]Finishing: Install dependencies

2023-07-19 14:34 UTC, maelle commented
I haven't seen this error but I think your workflow can just skip installing rotemplate, only pkgdown is needed.

2023-07-19 14:44 UTC, yjunechoe requested changes
Looks good! Just 2 small comments

2023-07-19 14:44 UTC, yjunechoe commented on R/oa2df.R
> +}
Should `out_df` be returned here (and else where in `publishers2df()` and `sources2df`?

```
  out_df <- rbind_oa_ls(list_df)
  out_df
}
```

2023-07-19 14:44 UTC, yjunechoe commented on R/oa2df.R
> +#' @inheritParams oa2df
Just realizing this and this goes for all the `*2df()` functions:

They all have the `verbose = TRUE` default, but the docs inherit the description for the `verbose` param from oa_query/oa_request, whose description says it defaults to `FALSE`:

```
#' @param verbose Logical. If TRUE, print information on querying process.
#' Default to \code{verbose = FALSE}.
```

To avoid confusion, should we override the documentation of the verbose param in `oa2df()` saying that it defaults to `TRUE`, and let that trickle down to the other `*2df()` that inherit from `oa2df()` (and also have `verbose = TRUE`)?

2023-07-19 14:50 UTC, trangdata commented on R/oa2df.R
> +#' @inheritParams oa2df
Thank you for catching this, June! Yes, I'll default this oa2df's verbose to TRUE.

2023-07-19 14:50 UTC, yjunechoe commented
Also apparently I [can't comment on unchanged files](https://github.com/orgs/community/discussions/9099) in my review, but we should also edit the `id_type()` internal that `oa_fetch()` uses to guess entity type if only `identifier` is provided:

https://github.com/ropensci/openalexR/blob/66f07433b5efbdff16c581da9fdb754fb649fb4b/R/utils.R#L59-L68

And maybe worth adding the failing ones here to tests once that's implemented:

``` r
# These work:
i <- oa_fetch(identifier = "I4200000001") # Institution
a <- oa_fetch(identifier = "A1969205032") # Author

# New ones don't yet:
f <- oa_fetch(identifier = "F4320332161") # Funder
#> Error in match.arg(entity, oa_entities()): 'arg' must be NULL or a character vector
p <- oa_fetch(identifier = "P4310311775") # Publisher
#> Error in match.arg(entity, oa_entities()): 'arg' must be NULL or a character vector
s <- oa_fetch(identifier = "S1983995261") # Source
#> Error in match.arg(entity, oa_entities()): 'arg' must be NULL or a character vector
```

2023-07-19 14:51 UTC, trangdata commented on R/oa2df.R
> +}
Yes! Good catch!

2023-07-19 16:38 UTC, trangdata commented
Ready for next round of review @yjunechoe 🙏🏽

2023-07-19 17:10 UTC, yjunechoe commented
All looks good to me! - You can go ahead and merge

One thing to watch out for which I think might just be on the API end is that _multiple_ entity search works for Source but not Funder and Publisher. Maybe they haven't implemented the OR filter by ID for them yet:

``` r
## These work
w2 <- oa_fetch(identifier = c("W2100837269", "W1775749144"))
s2 <- oa_fetch(identifier = c("S2764455111", "S4306400806"))

## These don't work
f2 <- oa_fetch(identifier = c("F4320332161", "F4320306076"))
#> Error: OpenAlex API request failed [403]
#> Invalid query parameters error.
#> <openalex_id is not a valid field. Valid fields are underscore or hyphenated versions of: cited_by_count, continent, country_code, default.search, description.search, display_name, display_name.search, from_created_date, grants_count, ids.crossref, ids.doi, ids.openalex, ids.ror, ids.wikidata, is_global_south, openalex, roles.id, ror, summary_stats.2yr_mean_citedness, summary_stats.h_index, summary_stats.i10_index, wikidata, works_count>
p2 <- oa_fetch(identifier = c("P4310311775", "P4310320990"))
#> Error: OpenAlex API request failed [403]
#> Invalid query parameters error.
#> <openalex_id is not a valid field. Valid fields are underscore or hyphenated versions of: cited_by_count, continent, country_codes, default.search, display_name, display_name.search, from_created_date, hierarchy_level, ids.openalex, ids.ror, ids.wikidata, lineage, openalex, parent_publisher, roles.id, ror, summary_stats.2yr_mean_citedness, summary_stats.h_index, summary_stats.i10_index, wikidata, works_count>
```

For example, the code for `f2` above generates this endpoint which returns an error:
- https://api.openalex.org/funders?filter=openalex_id:F4320332161|F4320306076

But the code for `s2` also uses the same syntax for Source entities and this works fine:
- https://api.openalex.org/sources?filter=openalex_id:S2764455111|S4306400806

Maybe we just wait to see if OpenAlex catches up on these soon :)

2023-07-19 17:10 UTC, yjunechoe approved these changes

2023-07-19 19:17 UTC, trangdata commented
Thank you for pointing this out, @yjunechoe! I notified the OpenAlex team. Hopefully, they'll fix this soon. 🤞🏽

2023-07-19 19:18 UTC, merged

2023-07-20 21:04 UTC, h1-the-swan commented
OpenAlex team member here. I have added the "openalex_id" filter to funders and publishers, which should fix this issue. Just FYI, though, I believe that that filter has been deprecated in favor of "openalex" (e.g., https://api.openalex.org/funders?filter=openalex:https://openalex.org/F4320306076), which is probably why it wasn't included in those newer entities.