Save pages returned by `oa_request()` and do not process fue=rther
ropensci/openalexR pull request #181
Opened 2023-10-20 11:24 UTC by rkrug

2023-10-20 11:49 UTC, yjunechoe reviewed
Thanks for the PR! I left a few minor (design-related) comments for your consideration (haven't tested out how the code runs yet).

2023-10-20 11:49 UTC, yjunechoe commented on R/oa_fetch.R
> +#' @param save_pages Character.
Two quick thoughts about `save_pages`:

1) I think the name could be a little clearer - people might confuse this with a toggle option taking T/F. Maybe something like `out_dir` that makes it explicit that it expects a directory path as value?

2) The argument description should ideally be concise and document just its function. The motivation and other notes (about memory issues, etc.) could move to its own `@section` or `@notes`

2023-10-20 11:49 UTC, yjunechoe commented on R/oa_fetch.R
> +    save_pages <- normalizePath(save_pages)
Do we perhaps want to `normalizePath()` before we potentially `dir.create()`?

2023-10-20 11:52 UTC, rkrug commented on R/oa_fetch.R
> +    save_pages <- normalizePath(save_pages)
Thought that as well - but it creates a warning if the directory dow=es not exists. But one could use `mustWork = FALSE`?

2023-10-20 12:00 UTC, yjunechoe commented on R/oa_fetch.R
> +    save_pages <- normalizePath(save_pages)
I've never used that argument before but I think that makes sense - basically, I think we'd prefer the path used for `dir.create()` and stored in `save_pages` to be exactly identical.

2023-10-20 12:00 UTC, rkrug commented on R/oa_fetch.R
> +#' @param save_pages Character.
1. Agreed. `out_dir` sounds a bit like where to save the output - which it is not. Rather `output_pages_to`?
2. OK - I will streamline it.

2023-10-20 12:01 UTC, yjunechoe commented on R/oa_fetch.R
> +#' @param save_pages Character.
Yeah `output_pages_to` sounds great!

2023-10-20 12:13 UTC, rkrug commented on R/oa_fetch.R
> +#' @param save_pages Character.
Changed in last commit

2023-10-20 12:47 UTC, trangdata requested changes
I'm not sure it's optimal to use `saveRDS` within the package. 

I'm currently working on a different branch on improving paging in `oa_fetch` and `oa_request`. Let me finish some final touches and perhaps you can help me test my implementation @rkrug? The idea is to use basic paging for fetching individual pages. Personally, I think this change would be a little less disruptive than `saveRDS`. I will give some examples in the PR. And whether we move forward with `output_pages_to` or not, I think my branch would still improve the paging implementation. 

Would love to hear your thoughts @rkrug @yjunechoe. Stay tuned!

2023-10-20 13:08 UTC, rkrug commented
From my experience with snowballing starting from more than 3000 papers, the limitation is really memory, i.e. the memory management of R. 
If one would download one page, then reserve the memory needed for one object to hold all data from all pages (e.g. `rep(ONE_PAGE_DATA_structure, n_pages`) by creating a dummy object and replacing after each page the page in the object, it could work - unless the final object is to large (and this would speed the process up as only one memory allocation is needed). 
But still - I guess that the total memory limit kicks in sooner or later. So the fallback solution of saving each page using `saveRDS` would be a safety net, which one could use if a) an argument is set, or b) the object containing the data I can not be created.


Just my thoughts, and looking forward to your pull request, @trangdata

2023-10-23 10:23 UTC, rkrug commented on R/oa_fetch.R
>                         count_only = FALSE,
This is not more than a proof of concept implementation.

2023-10-23 16:15 UTC, trangdata commented
> I'm also a little wary of using saveRDS. It's a weird middle ground between where you apply some but not all processing to the data received from OA.

@yjunechoe Not sure you saw [my comment](https://github.com/ropensci/openalexR/pull/183#issuecomment-1775085348) in my Improve paging control PR, but I'll reiterate it here:  at the moment, I think it's out of scope for openalexR to handle any type of serialization/IO. We currently provide enough flexibility for the user to do this themselves. 

In general, I think making many requests to the Open Alex database is not a common use case, and I would generally advise against it. One can [download the snapshot](https://docs.openalex.org/download-all-data/download-to-your-machine) themselves and proceed with the filtering/processing without needing openalexR.

Therefore, my current suggestion would be to close this PR.

2023-10-23 16:19 UTC, yjunechoe commented
Ah I'd missed the discussion going over there! Yes, I don't disagree with just closing this as out of scope (my comment was more of a "if we do implement this" comment)

2023-10-23 23:20 UTC, yjunechoe commented
Closing this as out of scope for the package, in favor of #183 and the continuing discussion on #182 (where we can resolve how to streamline this workflow without introducing too much maintenance burden). Apologies for my earlier confusion!

2023-10-23 23:20 UTC, closed without merging